### Hi there 👋

<!--
**MagnoliaSlimMarket/MagnoliaSlimMarket** is a ✨ _special_ ✨ repository because it is in need of unprecedented amounts of help with dreams of becoming a faster/"less of an ADHD Patient" Learner.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
